name: Gradify Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   #- name: Setup MSVC Developer Command Prompt
   #  if: matrix.os == 'windows-latest'
   #  uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
   #  with:
   #    arch: x64
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.4.3
        modules: qtcharts

    - name: Configure
      run: qmake -makefile src/Gradify.pro
      
    - name: Build
      run: make
