name: Gradify Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.4.3
        modules: qtcharts

    - name: Configure Project
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "Configuring MSVC"
          name: Configure MSVC
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: x64
            spectre: true
        fi
        qmake -makefile src/Gradify.pro

    - name: Build
      run: make || true
      continue-on-error: true

    - name: Test
      run: make test || true
      continue-on-error: true

    - name: Package
      run: make install || true
      continue-on-error: true
