name: Gradify Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.4.3
        modules: qtcharts

    - name: Configure MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        spectre: true
        
    - name: Configure Project
      run: qmake -makefile src/Gradify.pro

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Package
      run: make install
