name: Build Qt C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Debug PATH
      run: |
        echo "PATH = $PATH"

    - name: Debug Step
      run: |
        echo "Debugging step: Before finding qmake"
        qmake_path=$(which qmake)
        echo "QMAKE_PATH=$qmake_path" >> $GITHUB_ENV
        echo "Debugging step: After finding qmake"
        echo "::set-output name=qmake-path::$qmake_path"
        echo "Debugging step: After setting output"
      
    - name: Set Up Qt
      run: |
        echo "Debugging step: Before setting up Qt"
        sudo apt-get update
        sudo apt-get install qt6-default
        export QMAKE=${{ env.QMAKE_PATH }}
        echo "Debugging step: After setting up Qt"

    - name: Build Project
      run: |
        echo "Debugging step: Before building project"
        qmake -r
        make
        echo "Debugging step: After building project"

    - name: Upload Artifacts
      if: success()
      run: |
        echo "Debugging
